// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9g9Por3znGksLG8GL_tXh3Wk3faphSk',
    appId: '1:428332828375:web:8c9ff52696c91ed9851292',
    messagingSenderId: '428332828375',
    projectId: 'proyectolinea2-723a4',
    authDomain: 'proyectolinea2-723a4.firebaseapp.com',
    storageBucket: 'proyectolinea2-723a4.appspot.com',
    measurementId: 'G-MSKM942L2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6AZKm7cBoI8sXgTRD0RmFL2UroWL93QY',
    appId: '1:428332828375:android:cbe2d74370c0c6fd851292',
    messagingSenderId: '428332828375',
    projectId: 'proyectolinea2-723a4',
    storageBucket: 'proyectolinea2-723a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUkmEhmmT91IR9yLE-ZOg8kVTvCpURmY0',
    appId: '1:428332828375:ios:962c1b5d0e5f2636851292',
    messagingSenderId: '428332828375',
    projectId: 'proyectolinea2-723a4',
    storageBucket: 'proyectolinea2-723a4.appspot.com',
    iosClientId: '428332828375-u2j1u3emm1havgd7bcdvfl3hkav3q407.apps.googleusercontent.com',
    iosBundleId: 'co.edu.ucundinamarca.proyectobaselinea20222',
  );
}
